-- ============================================================================
-- File:    mock_data/03_validation.sql
-- Purpose: Sanity checks on the mock P&C dataset.
-- ============================================================================

-- Row counts
SELECT 'DIM_DATE'         AS TABLE_NAME, COUNT(*) AS "ROWS" FROM DIM_DATE
UNION ALL SELECT 'DIM_GEOGRAPHY',          COUNT(*) FROM DIM_GEOGRAPHY
UNION ALL SELECT 'DIM_PRODUCT_LOB',        COUNT(*) FROM DIM_PRODUCT_LOB
UNION ALL SELECT 'DIM_COVERAGE',           COUNT(*) FROM DIM_COVERAGE
UNION ALL SELECT 'DIM_AGENT',              COUNT(*) FROM DIM_AGENT
UNION ALL SELECT 'DIM_POLICYHOLDER',       COUNT(*) FROM DIM_POLICYHOLDER
UNION ALL SELECT 'FACT_POLICY',            COUNT(*) FROM FACT_POLICY
UNION ALL SELECT 'FACT_PREMIUM_TXN',       COUNT(*) FROM FACT_PREMIUM_TXN
UNION ALL SELECT 'FACT_CLAIM',             COUNT(*) FROM FACT_CLAIM
UNION ALL SELECT 'FACT_LOSS_RESERVE',      COUNT(*) FROM FACT_LOSS_RESERVE
ORDER BY 1;

-- Referential integrity (should return 0 rows each)
SELECT 'POLICY -> POLICYHOLDER' AS CHECK_NAME, COUNT(*) AS ORPHANS
FROM FACT_POLICY p
LEFT JOIN DIM_POLICYHOLDER ph ON p.POLICYHOLDER_KEY = ph.POLICYHOLDER_KEY
WHERE ph.POLICYHOLDER_KEY IS NULL
UNION ALL
SELECT 'POLICY -> AGENT', COUNT(*)
FROM FACT_POLICY p
LEFT JOIN DIM_AGENT a ON p.AGENT_KEY = a.AGENT_KEY
WHERE a.AGENT_KEY IS NULL
UNION ALL
SELECT 'CLAIM -> POLICY', COUNT(*)
FROM FACT_CLAIM c
LEFT JOIN FACT_POLICY p ON c.POLICY_KEY = p.POLICY_KEY
WHERE p.POLICY_KEY IS NULL
UNION ALL
SELECT 'PREMIUM_TXN -> POLICY', COUNT(*)
FROM FACT_PREMIUM_TXN x
LEFT JOIN FACT_POLICY p ON x.POLICY_KEY = p.POLICY_KEY
WHERE p.POLICY_KEY IS NULL;

-- Loss-ratio sanity (overall)
SELECT
    SUM(c.PAID_LOSS + c.CASE_RESERVE) / NULLIF(SUM(x.EARNED_PREMIUM), 0) AS LOSS_RATIO
FROM FACT_CLAIM c
CROSS JOIN FACT_PREMIUM_TXN x;
